### ISSUE TITLE
Sidebar: Add link to feedback form 

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#101]
Could we make the feedback form available once people leave the landing page? If they didn't open it then, how will they find the feedback form again?

**Comment by dangeol** [comment]
![image](https://user-images.githubusercontent.com/44405794/75096473-3aed9b00-55a0-11ea-9ffc-ef554d3eed01.png)
![image](https://user-images.githubusercontent.com/44405794/75096481-493bb700-55a0-11ea-894d-c33f4b733769.png)

**Comment by MarcusGaleotti** [comment]
I would like to work on this, but don't see an option to assign myself

**Comment by johnwang16** [comment]
I can't seem to assign anything to myself either.. if you want to work on it go right ahead. If you need any help or pointers where to start feel free to ping me

**Comment by shraddha314** [comment]
The give feedback form is visible in all pages and works. This is great - Thank you.
