### ISSUE TITLE
Lost of the context of navigation 

### ISSUE THREAD

**Issue by MartineMK35** [parthopdas/digitalpalireader#104]
Example : I'm reading MN3. I want to make a search. When I go back to the navigation , the context is lost. I have go reenter everything to continue the reading

**Comment by bksubhuti** [comment]
should at least enable control +click for new window at minimum

**Comment by dangeol** [comment]
In the navigation tab, a user selects a Set, a Book, and hits the arrow button of a Section and reads the text. He then switches to the Search tab and performs a tab. The content is replaced by the search results, and when going back to the Navigation tab, the selection is still there but of course the text he was reading has been replaced by the search. @MartineMK35 is this the correct description?

**Comment by johnwang16** [comment]
I think the search should have the results open in a new tab to be less disruptive to the end user, but that's up to the stakeholders to make that call. 

When I navigate back from a search it returns me back to the section I was reading, so I'm not seeing any problems there. If @MartineMK35 is seeing any type of inconsistencies in history navigation behavior please let us know as I'd like to make sure the popstate handler isn't missing any use cases.

**Comment by MartineMK35** [comment]
Yes Daniel That's the correct description.
The best would be to have a new window for the research

Le sam. 22 févr. 2020 à 20:03, Daniel Oellers <notifications@github.com> a
écrit :

**Comment by dangeol** [comment]
Ok thanks @MartineMK35.

**Comment by dangeol** [comment]
Now it's not working properly for me. Clicking on the "arrow left" and "arrow right" previous/next section buttons and "m", "a", "t" button only works once, thenit's doing nothing.
