### ISSUE TITLE
[UI Restructuring work] 3rd screen  should be resizeable (regression)

### ISSUE THREAD

**Issue by MartineMK35** [parthopdas/digitalpalireader#105]
What i call 3rd screen is the screen where I find the dictionnary definitions and the grammatical declention.

Dictionnary definition are large. It's importance not to scroll too much. and also to see all the declention is usefull.

**Comment by parthopdas** [comment]
Thanks @MartineMK35. I have included this as part of #127 and it will be fixed shortly for beta.
