### ISSUE TITLE
Search Textbox (and all text boxes) should have Enter-Key event

### ISSUE THREAD

**Issue by bksubhuti** [parthopdas/digitalpalireader#110]
Search Textbox and all texts boxes should automatically execute when the <Enter Key> is pressed.  It is so logical, it seems like a bug if not implemented.
It is easy to catch and then call an event and makes a big difference.

**Comment by dangeol** [comment]
Hitting enter key in search text boxes works for me in latest versions of Chrome and Firefox in Windows 10.

**Comment by bksubhuti** [comment]
yup.. true.  I am using Epiphany from eOS and also Gnome.

**Comment by parthopdas** [comment]
this should be fixed. please check and reactivate if necessary.
