### ISSUE TITLE
Feedback form enhancements for alpha

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#111]
1. Upload images (https://sites.google.com/site/scriptsexamples/home/announcements/google-forms-file-upload-feature)
2. URL autofill

**Comment by dangeol** [comment]
Who is in charge of this?

**Comment by parthopdas** [comment]
@dangeol it is on me. assigned it to myself.

**Comment by parthopdas** [comment]
Could not figure out a way to add screenshots though.
