### ISSUE TITLE
There are multiple issues when running the base index.html file through https://validator.w3.org by direct input

### ISSUE THREAD

**Issue by MarcusGaleotti** [parthopdas/digitalpalireader#117]
The W3C Markup Validation Service for XHTML 1.0 Strict finds upwards of 96 errors and some warnings as of the time of this writing. Though most browsers are lenient, it is advisable to have these resolved/cleaned up at some point to conform to the standard and make functionality more likely to be consistent. 

Some of these are due to custom attributes being set on elements, which may be ignorable assuming they are used for some specific application purpose.

**Comment by parthopdas** [comment]
Thanks @MarcusGaleotti I have included this as part of #96
