### ISSUE TITLE
DPRv1 parity issues found during testing

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#118]
1. cannot click on individual nav items on search results page header
1. from search, clicking to navigate, the "search hit" is hidden/overshot
1. sanskrit dictionary
1. sanskrit roots

**Comment by dangeol** [comment]
> dictionary - clear main pane

What do you exactly mean?

**Comment by parthopdas** [comment]
@dangeol - i forgot what i noted down. i'll strike that out for now and add it back if i recall.

**Comment by parthopdas** [comment]
@shraddha314 please verify and reactivate if issue are present.

**Comment by parthopdas** [comment]
@shraddha314 please verify and reactivate if issue are present.
