### ISSUE TITLE
?loc=d.0.m should behave the same was as the XUL

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#17]
Two issues are tracked through this:
1. The [web version](https://dprstaging.z24.web.core.windows.net/DPRHTML/index.html?loc=d.0.m) does not behave the same was as the chrome://digitalpalireader/content/index.xul?loc=d.0.m
2. Do we have similar other inconsistencies? If so fix them.

**Comment by johnwang16** [comment]
The fix for this is pending here https://github.com/johnwang16/digitalpalireader/commit/2e028484d75ac69cfdbbe4c226191b43f52e1a1f

**Comment by smkvr98** [comment]
lines relevant to this issue(part 1.) from @johnwang16 commit : #21

**Comment by parthopdas** [comment]
@smkvr98 please check once more if we have missed out any other url formats. if not close the issue, esle send PR.

**Comment by smkvr98** [comment]
2nd commit in #43 addresses this .

**Comment by dangeol** [comment]
?loc=d.0.m behaviour was fixed by #43
