### ISSUE TITLE
Implement basic menu in the sidebar

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#19]
While we sort out the final app structure, we need a temporary way to navigate between "Navigation", "Search" & "Dictionary".

Need to implement that in the sidebar.

**Comment by parthopdas** [comment]
@dangeol my bad - i forgot that i filed this issue so i pushed a quick fix in time for today's meeting.

it looks like this
![image](https://user-images.githubusercontent.com/2140460/73122685-5ed6b480-3fd3-11ea-8456-9d087651445e.png)

Hope you dont have a lot of throw away work. sorry about that.

**Comment by dangeol** [comment]
Basic sidebar is implemented, this issue can be closed.
