### ISSUE TITLE
Enable building on windows

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#20]
Please add `sanskrit/content/` and `node-modules/` to `.gitignore`. The sanskrit/content/ folder contains filenames coming from Linux as a case-sensitive environment, which cause case conflicts in case-insensitive environments such as Windows.

**Comment by parthopdas** [comment]
ok @dangeol i deleted dprhtml/extensions as it was dead code so node_modules is gone.

however can you check i adding to gitignore works on your windows machine? in my understanding, git will still checkout the files - just that new files will not be tracked.

**Comment by dangeol** [comment]
Thanks, I will try this. I assume that I will need to re-clone the repository.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by parthopdas** [comment]
Essentially need to handle sanskrit/content/ check out on windows + switch to windows on the ado build machines.

**Comment by bksubhuti** [comment]
I think need to remove build altogether .  I made a new issue about this.

**Comment by parthopdas** [comment]
Builds on windows now.
