### ISSUE TITLE
Fix dictionary: Make various combinations work

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#32]

**Comment by dangeol** [comment]
https://github.com/parthopdas/digitalpalireader/commit/5d07ffd25baac898c3f99a124aa36307e283fc1e implements all dictionary functionalities except for DPR analysis which does not yet work:

- deep links don't work for DPR analysis
- using the search button for DPR analysis only works once correctly; from the second time, the content div `difb` of the bottom panel is not refreshed with new content

Attention: in both `index.html` and `dictionary-results` there is a div named `divb`.
