### ISSUE TITLE
Switch back to history.pushState in DPRChrome.openDPRTab

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#35]
history.pushState was originally used so as to not refresh the page.

however if you see history.pushState does not update the page when url params changes. e.g. when you change dict search options and hit search button, url gets updated by not the page.

any idea what might be happening?
for now i have just use location.href but its ugly as the entire page refreshes.
any idea what is a better fix?

**Comment by johnwang16** [comment]
history.pushState only adds a url to the browser history. Changing the window content still needs to be implemented in order for anything to happen. See https://github.com/johnwang16/digitalpalireader/commit/d9a846e97aa8715bd32e41f1597266fee9643684 for the implementation on dict and search pages

**Comment by dangeol** [comment]
Since https://github.com/parthopdas/digitalpalireader/commit/5d07ffd25baac898c3f99a124aa36307e283fc1e, `history.pushState` is back in use. The behaviour seems to be consistent with the DPRv1 except of analysis, for which url changes are not working, which is not related to `history.pushState`.
