### ISSUE TITLE
Search and Dictionary: Results sometimes not scrollable

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#39]
The search behaves a bit strangely. When searching for certain terms the main pane is scrollable whereas when searching some other terms the main pane where the search results show up is not scrollable and I can only see whatever is visible - it is not possible to scroll down to see everything. Try searching "kaya" (main pane scrollable) and "cula" (main pane not scrollable).

Regarding the Dictionary: The results page is generally not scrollable. Test with "kar".

**Comment by shraddha314** [comment]
Verified its working on staging
