### ISSUE TITLE
Navigation, quick links: sending away of help box 

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#42]
Quick links: Once you click on the ? and the box with description appears, it is not easy to send that box away. Clicking in other places does not work - we have to click on the ? button again.
The box should go away by clicking elsewhere. Also, make the tooltip style consistent with all the other tooltips.

**Comment by smkvr98** [comment]
@dangeol #43 hopefully addresses this . Please review .

**Comment by dangeol** [comment]
Closed by #43
