### ISSUE TITLE
Sidebar: some bugs regarding opening and closing of sidebar

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#44]
- When clicking the link to the sidebar for the first time, the sidebar comes up, the rest of the page goes blank and there is no way to go back. Also the sidebar takes a while to load the first time everything is blank. Suggest keeping the initial instructions on the main pane.

- When clicking a link from the search results, the side bar shows up (instead of staying collapsed).

- Side bar does not collapse automatically when using the dictionary as it does when using the navigation and search.

- Sometimes nothing happens when clicking on the sidebar link (the three lines)

**Comment by parthopdas** [comment]
@shraddha314 i checked and the 4 issues listed above dont happen on staging anymore. can you please confirm

**Comment by parthopdas** [comment]
@shraddha314 please reactivate if these issues are still present on staging.
