### ISSUE TITLE
Dictionary issues

### ISSUE THREAD

**Issue by MaxxJohnson** [parthopdas/digitalpalireader#50]
As of Sunday 2/9/20 it seems the dictionary is less functional than before.

-I can’t get the case button to work

-Dictionary pane sometimes doesn’t load detailed definition information anymore (however still shows quick definition on top line of pane.) Clicking on the searched word on the top left line of dictionary pane does not make the detailed info pane below respond by bringing up the definition. For example, when clicking on either of the parts of a compound word.

-When clicking on bar to hide/show dictionary pane it often opens and closes 3 times (sometimes fewer) before remaining open or closed.

-After leaving the browser page (safari on iOS) temporarily to do other activity on my phone, upon return to the browser page that has DPR loaded the dictionary pane becomes blank and does not contain the previously visible searched word and definition.

**Comment by dangeol** [comment]
@MaxxJohnson thanks a lot for this detailed feedback. 

> ...  less functional than before.

I would be interested in when "before" was. Throughout last week several changes were applied. We should try to revert back to the situation when you saw it working better last time.

**Comment by MaxxJohnson** [comment]
“Before” was approx. 12 hours before that post. After speaking with Sumukha, a few hours after this original post, everything was pretty much fixed except for some green “n” proper noun buttons not working. Then shortly after they appeared fixed, things reverted to their dysfunctional state. I assume Sumukha is working on different fixes for now. This dysfunction is on chrome and safari for iOS. Thanks for all the work everyone!

**Comment by MaxxJohnson** [comment]
-It seems case button in DPR analysis begins to work after doing at least one search using any of the other searches in drop down i.e. PED, Pāli Roots

**Comment by MaxxJohnson** [comment]
-As mentioned above, the case button (green “c” to the right of word in dictionary pane) does not work after searching a word using DPR analysis

**Comment by parthopdas** [comment]
@shraddha314 i had a call with @MaxxJohnson and we went through each items listed above.

Summary:
1. All issues are fixed as of today
2. The only fix I made yesterday was for the 'c' issue.

Please verify and close.

**Comment by shraddha314** [comment]
Checked and it looked like it is fixed
