### ISSUE TITLE
Dictionary: misc bugs concerning layout/behaviour

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#53]
1. ~~When clicking on an item of the PED full-text search result page, the top navigation bar disappears~~ fixed by https://github.com/parthopdas/digitalpalireader/pull/86

2. ~~When clicking on book references in term search or title search results, a new tab is opened instead of the current one reused~~ this is actually consistent with DPRv1

3. ~~Sometimes, when clicking on a word in the text, and by clicking the dictionary search button, the bottom frame double angle up/down symbol rotates, but shouldn't. Reproduce by clicking on words here: http://127.0.0.1:8080/DPRHTML/index.html?loc=g.3.0.0.5.0.0.m&para=9&analysis=accuccasaddo~~ as of 2020-02-20 can't reproduce this any more

4. ~~When doing a "PED, DPPN & CPED" term search and then clicking on a term, the bottom frame should open if it's closed, but doesn't. Alternatively, the results should be displayed in the main frame instead of the bottom frame.~~ Tracked by #77 

5. When a book section text is displayed in the main frame, and you then perform a DPR analysis by entering a search term and clicking on `dictButton`, the main frame div `paliTextContent` is cleared. However, when just hitting enter key instead of clicking on `dictButton`, the content is not cleared. The content should not be cleared.

**Comment by dangeol** [comment]
@parthopdas could you please give your input on point 4.

**Comment by parthopdas** [comment]
@dangeol if there are no serious objections to the current inconsistent behavior, i'd leave it as it is. then depending on the feedback from alpha - we'll fix it.

**Comment by dangeol** [comment]
Why is @johnwang not here in the assignee list, but on issues on the first page he is?
