### ISSUE TITLE
Search: broken functionality for strings containing diacritics

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#61]
The letters with diacritical marks are converted into a UTF-8 hex format, causing troubles. This bug must have been introduced recently.
Using commit #408039f from three weeks ago, this bug was not yet there. This screenshot shows the problem for the search string **dāna**.
![2020-02-16 14_17_01-Search_ 'd%C4%81na' in Multiple Sets](https://user-images.githubusercontent.com/44405794/74605292-1e94be80-50c7-11ea-9b7e-5b54ff2fc8ce.png)

**Comment by dangeol** [comment]
please see https://github.com/parthopdas/digitalpalireader/issues/60

**Comment by parthopdas** [comment]
another test case: karaṇīya

**Comment by parthopdas** [comment]
Transferred into to #56 and #60. Close this as dup.
