### ISSUE TITLE
Broken Local Build

### ISSUE THREAD

**Issue by bksubhuti** [parthopdas/digitalpalireader#65]
The local build does not work by itself.
Actually the project for HTML and web should be separated and a clean build should be made.
This is a high priority because the root build does lots of unneccessary things and is a security risk.  Very undesirable to run for potential helpers.

Yarn should be listed as needed to be installed, but if these resultant files are text files then best to just include them in the project.  IF they are binary.  Include a note that these files need to be built and yarn needs to be installed.  

The ability to build a system is essential and basic and critical root problem.

**Comment by parthopdas** [comment]
works as discussed, please reactivate if not.
