### ISSUE TITLE
Landing page issues

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#69]
1. For the first point, suggest rephrasing to: To start, open the sidebar then choose a Set, Book, Book Hierarchy and click the => button to see the contents.
1. Add it may be helpful to add the second way to see the contents: You could also view the sutta by directly entering the Set shortname and Sutta number (for instance mn 10) in quick links.
1. Remove this for alpha: For detailed instructions, click here for the help page.
1. Remove this and add the feedback form. "If you have questions or feedback, send email to yuttadhammo+dpr@gmail.com."
1. [TBD by @shraddha314] Create a new dpr email address and create a feedback form

**Comment by parthopdas** [comment]
done with 1 to 4. waiting on @shraddha314 for the rest.

**Comment by shraddha314** [comment]
Verified its working on staging. You already linked the feedback form. It does look a bit strange with the ... after contact us. Maybe leave it at "contact us" or say "contact us here"

**Comment by parthopdas** [comment]
> Verified its working on staging. You already linked the feedback form. It does look a bit strange with the ... after contact us. Maybe leave it at "contact us" or say "contact us here"

Removed the ellipsis.
