### ISSUE TITLE
Navigation: Honor deep links

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#7]
index.html should honor deep links.

E.g. http://127.0.0.1:8080/DPRHTML/index.html?loc=v.1.0.0.0.0.0.m should open up the correct page. Right now blank index.html opens up.

**Comment by dangeol** [comment]
Is this still an issue? I get the correct page when putting a loc parameter.

**Comment by parthopdas** [comment]
first level already done by @johnwang16.
