### ISSUE TITLE
Main Pane: macOS: Could you make the scroll bar visible?

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#76]

**Comment by parthopdas** [comment]
@shraddha314 
i investigated and it appears it is a deliberate UI paradigm in macOS where the scrollbars are not show unless necessary i.e. unless one attempts to scroll.

the same issue also existed in the book/set lists, however i fixed it by "always showing the scrollbars" as IMO it was more of an issue there given how non-obvious it was..

Please reactivate if in your opinion we need to fix this.

**Comment by shraddha314** [comment]
Scrollbar showing in book/set. Not showing in main pane but its ok - it shows up when clicking on the window.
