### ISSUE TITLE
Dictionary: DPR analysis results are always shown in the bottom pane. This is not consistent with DPRv1

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/digitalpalireader#77]
[Split from #53]
4. To be discussed: DPR analysis results are always shown in the bottom pane. This is not consistent with DPRv1 where sometimes - depending on the context - results are shown in the main pane. However this was for me a way to quickly establish this functionality, as there were two divs with identical id `divb` which caused trouble, and I renamed one of them to `divb2`.

This must be also covered by this issue (was tracked by https://github.com/parthopdas/digitalpalireader/issues/53):
When doing a PED, DPPN or CPED, or combined term search and then clicking on a term, the bottom frame should open if it's closed, but doesn't. It should automatically open. Alternatively, the results should be displayed in the main frame instead of the bottom frame.

**Comment by dangeol** [comment]
Can we move this discussion to beta?

**Comment by parthopdas** [comment]
> Can we move this discussion to beta?
Hi @dangeol IMO we should keep this for alpha as this is a parity issue. i.e. users will be expecting something in dprweb but finding something else. In addition currently this appears in the bottom pane which does not expand by default - so that is further confusing.

let me know what you think.

**Comment by dangeol** [comment]
Ok. The issue that the bottom pane does not expand when clicking on terms will be covered by https://github.com/parthopdas/digitalpalireader/issues/53. This was marked as alpha in the spreadsheet, but not here until yesterday. Sorry for that.

**Comment by parthopdas** [comment]
@shraddha314 this should be fixed now. please let me know if you require clarification.

**Comment by dangeol** [comment]
Clicking on words in the text for DPR Analysis does not show content in bottom frame.
