### ISSUE TITLE
Remove xpi artifacts + build

### ISSUE THREAD

**Issue by bksubhuti** [parthopdas/digitalpalireader#79]
AC:
- [ ] Delete XUL specific artifacts
- [ ] Remove building and publishing of xul artifcats
- [ ] Modify build/release pipeline appropriately

Original comment:
It seems there is a need for xpi files.
These should be zip html xml files of the tipitaka (that is all an xpi is).

**Comment by bksubhuti** [comment]
It should be noted that this project is still palemoon dependent as long as this issue is not fixed.

**Comment by dangeol** [comment]
Will be done after alpha.

**Comment by bksubhuti** [comment]
This is already actually completed.  I use the live-server locally and never built any file or xpi.
