### ISSUE TITLE
Remove the "Build" idea

### ISSUE THREAD

**Issue by bksubhuti** [parthopdas/digitalpalireader#80]
Remove the whole concept of "build" from the html project.
It is html, it does not need a build

Any 3rd party libraries if needed should be requested from the original source.  I still have not gotten a working project to know what is needed and not needed and .. I suspect nobody knows  but ven Yuttadhammo.  There is no reproducibility or ability to be independent.

**Comment by bksubhuti** [comment]
Need to depreciate the xpi from this project.  Also need to update the README.md file to include DPR web up top

**Comment by parthopdas** [comment]
Build will be required in some form. As we need to be able to minify/run linters/tests etc.

I will be pulling in yarn/webpack based build shortly
