### ISSUE TITLE
Context menu: clicking on up arrow button shows unclickable button

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#87]
In the Context Menu, when you click Up Arrow (open book index) the menu shows a lonely lower case "s" which is unclickable. Clicking on it should open the Search tab.

Update 2020-02-22 (Shraddha): When going through navigate book heirarchy if using three lines button to view full sutta instead of by chapter (pressing arrow), the context menu shows only "s" that is unclickable.

**Comment by parthopdas** [comment]
@shraddha314 please verify and let us know.

**Comment by shraddha314** [comment]
@parthopdas this error does not happen but none of the context menu buttons work anymore.
