### ISSUE TITLE
Stuck in sections

### ISSUE THREAD

**Issue by bksubhuti** [parthopdas/digitalpalireader#92]
If I got to Vinaya Piṭaka mahāvaggapāḷi1. mahākhandhako
8. mārakathā

Then I am stuck there.  If I click on higher level mahākhandhako mahāvaggapāḷi it should bring up the whole book which is quite a load too.  It brings me into the same section ( mārakathā) when I click on mahākhandhako.

Need to go to navigation window to go to the next section.  Since the sections are short at times, this is tedious and a hindrance to reading flow, or searching for something manually.

Perhaps have  next and previous sections links?

This was based on the https://dprstaging.z24.web.core.windows.net/DPRHTML/index.html?loc=v.3.0.0.0.0.7.m&analysis=tenupasa%22nkami

The official website is down.   digitalpalireader.online

**Comment by bksubhuti** [comment]
I figured out that the next section can be navigated from the menu panel by pressing on the arrows.  It would be good if the arrows were moved to the base text or dictionary panel for better flow of reading.

**Comment by dangeol** [comment]
Is on par with original DPR. I added it to our pipeline list and close this issue.
