### ISSUE TITLE
[Build restructuring] README.md should have DPR Web at the top

### ISSUE THREAD

**Issue by bksubhuti** [parthopdas/digitalpalireader#97]
The readme.md file should have DPR Web at the top of the readme.
When it mentions XPI and build (below), it should say "depreciated" or "No longer in development"

DPR Web is spelled wrong as DRP Web

A previous issue was raised with removing the xpi project from the git or forking off without that stuff, or just deleting it.

**Comment by parthopdas** [comment]
Fixed in af7d159.
