### ISSUE TITLE
Remove bin from Repo 

### ISSUE THREAD

**Issue by bksubhuti** [parthopdas/digitalpalireader#98]
As a test, I ran live-server without the microsoft dll's accessible in my virtualbox folder.
They are seem to only be  needed for the microsoft stuff.
Maybe the sub folders as well.

I did leave the jsdll there.  But I'm pretty sure they cannot load in a linux environment anyway.

If they are needed, the instructions should be given where to download these files in the readme.
They are not needed for this project.

**Comment by parthopdas** [comment]
done
