### ISSUE TITLE
Context menu: improvements

### ISSUE THREAD

**Issue by dangeol** [parthopdas/digitalpalireader#99]
1. The context menu should either automaticall collapse back after being clicked or the main pane should be resized to show all content. Right now it blocks the content so we need to collapse it manually. [Not for alpha: The second option of resizing main pane maybe preferred in this case when using to go through the sections if we can make the side bar a little skinnier. ]

2. Can we remove the title context menu? What does context menu mean?

**Comment by parthopdas** [comment]
@dangeol @shraddha314 does this need to be fixed for alpha? i realize its not the most well behaved context menu, but we are going find it a good home in beta anyways?

**Comment by shraddha314** [comment]
@parthopdas @dangeol none of the buttons on the context menu seems to be working right now.

**Comment by dangeol** [comment]
I reopen this issue because the buttons don't work on everybody's system. As of Feb 26, it's working for @dangeol and @smkvr98 but it's not working for @shraddha314 and @parthopdas .

**Comment by dangeol** [comment]
Now it's not working properly for me. Clicking on the "arrow left" and "arrow right" previous/next section buttons and "m", "a", "t" button only works once, then it's doing nothing.
